### ISSUE TITLE
Enhancement Request: Allow looping through List value providers

### ISSUE THREAD

**Issue by nbrown30** [benahm/TestDataFactory#11]
When creating records in bulk it would be helpful to provide a smaller list of values and have them reused in the output.

For example:
```java
List<Book__c> myBooks = TestDataFactory.createSObjectList('Books__c', new Map<String, Object>{
    'Author__c' => new List<String>{'Vonnegut', 'Bukowski', 'Herbert', 'Murakami'},
    'Title__c'  => 'Book-{!index}'
}, 100);

/*
* Ideal output would look like:
*
* Book__c{author__c='Vonnegut', title__c=Book-1}
* Book__c{author__c='Bukowski', title__c=Book-2}
* Book__c{author__c='Herbert', title__c=Book-3}
* Book__c{author__c='Murakami', title__c=Book-4}
* Book__c{author__c='Vonnegut', title__c=Book-5}
* etc.
*/
```

Currently, if you were to write code like the above you end up with an out of bounds error:
`TestDataFactoryException: Unable to get the value for the field "author__c"`

Using a modulus operation (or something similar) to loop through a list would reduce the amount of code to initialize records while also giving variety to a large group of created records.

**Comment by benahm** [comment]
Hello @nbrown30  

Nice suggestion, thanks for reporting this feature request
I will let you know when it's implemented 👌

Ahmed

**Comment by benahm** [comment]
Hello @nbrown30 

Almost a year later, the feature is now implemented in the `TestDataFactory` 😃 

Again, thank you for your suggestion 👍
