### ISSUE TITLE
Some SObject types are not supported

### ISSUE THREAD

**Issue by jverce** [benahm/TestDataFactory#12]
## Description
There are some SObject types that cannot be instantiated through this factory. Some of those errors are related to required fields missing. I think the only workaround would be to explicitly set those missing attributes to something?

### `ActiveScratchOrg`
- **Code**
```apex
TestDataFactory.createSObject('ActiveScratchOrg');
```
- **Error**
```
TestDataFactory.TestDataFactoryException: Unable to insert "ActiveScratchOrg" records: REQUIRED_FIELD_MISSING: Required fields are missing: [ScratchOrg] []
```

### `ContentVersion`
- **Code**
```apex
TestDataFactory.createSObject('ContentVersion');
```
- **Error**
```
TestDataFactory.TestDataFactoryException: Unable to insert "ContentVersion.contentdocument" records: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY: An unexpected error occurred. []
```

### `DuplicateRecordSet`
- **Code**
```apex
TestDataFactory.createSObject('DuplicateRecordSet');
```
- **Error**
```
TestDataFactory.TestDataFactoryException: Unable to insert "DuplicateRecordSet" records: REQUIRED_FIELD_MISSING: Specify a value for the Duplicate Rule ID field. []
```

**Comment by benahm** [comment]
Hello @jverce 

Thanks for these extreme 🤯 tests 👍 

The Test Data Factory uses the [Apex Describe](https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_dynamic_describe_objects_understanding.htm)
I this sometime it there can be some incoherence in the describe 

![image](https://user-images.githubusercontent.com/3356566/104946832-07d3a780-59bb-11eb-861a-76065a038be1.png)

I personally did not try creating those objects, but yes, you can try specifying the tricky fields manually 

Example 

`TestDataFactory.createSObject('DuplicateRecordSet', new Map<String,Object>{
  'DuplicateRuleId' => '{valute}'
});`

Ahmed
