### ISSUE TITLE
Missing comma in the "Create a list of 5 Account sObjects with different names and a same description" example

### ISSUE THREAD

**Issue by kensation** [benahm/TestDataFactory#13]
On the examples page, the example for "Create a list of 5 Account sObjects with different names and a same description" is missing a comma after the object in the construction of the map.

It should look like:

```
List<Account> accList = TestDataFactory.createSObjectList('Account', new Map<String,Object>{
  'Name' => new List<String>{'Google','Amazon','Facebook','Apple','Microsoft'},
  'Description' => 'Same description'
},5);
```

**Comment by benahm** [comment]
Hello @kensation 
I've just made the fix, thank you for reporting 👍
