### ISSUE TITLE
Question: How can TestDataFactory be setup for custom SObjects?

### ISSUE THREAD

**Issue by chazwatkins** [benahm/TestDataFactory#14]
Hi @benahm - Well done on this library.  It seems easy to use and will definitely be useful in my org.  Can you provide an example of how to use the framework for custom objects?  It isn't clear how to define default values for custom objects.

**Comment by benahm** [comment]
Hello @chazwatkins 

It is similar to using it with the Standard objects, you just need to adapt the field/relationship name with the __c & __r 

Let's suppose you have a FirstObject__c that has a lookup to a SecondObject__c 

You can create the first & second object using the `TestDataFactory`

```
TestDataFactory.createSObject('FirstObject__c', new Map<String, Object>{
       Description__c => 'value for description field on FirstObject__c',
       LookupToSecondObject__r.Description__c =>  'value for description field on FirstObject__c'
})
```
This creates a record for the FirstObject with a related record of the SecondObject

Hope this help

Ahmed

**Comment by chazwatkins** [comment]
Thanks for the help, Ahmed.
