### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by reignman5** [benahm/TestDataFactory#15]
Hey,

Im getting the following error installing through UI.

![image](https://user-images.githubusercontent.com/56387018/132310776-43bc1a6f-bca6-43d0-a631-cdb57c0b0863.png)

Also not working using sfdx

**Comment by benahm** [comment]
Hello @reignman5 

Thank you very much for reporting this issue 👌

I just committed the fix ✅, the package ID had an extra leading zero 

Ahmed
